services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: inex-tracker
    container_name: inex-tracker-app
    restart: unless-stopped
    ports:
      - '8000:80'
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: inex_tracker
      DB_USERNAME: root
      DB_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules

  db:
    image: mysql:8
    container_name: inex-tracker-db
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: inex_tracker
      MYSQL_ROOT_PASSWORD: admin
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -p$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
